 ### Covariance Matrix Computation

In [6]:
import numpy as np

marks = np.array([[90, 90, 60, 60, 30], [60, 90, 60, 60, 30], [90, 30, 60, 90, 30]])

mean_marks = np.mean(marks, axis = 1)
mean_marks

array([66., 60., 60.])

In [7]:
CovMat = np.cov(marks, bias=True)
CovMat

array([[504., 360., 180.],
       [360., 360.,   0.],
       [180.,   0., 720.]])

In [8]:
eig_val, eig_vec = np.linalg.eig(CovMat)
eig_val

array([ 44.81966028, 910.06995304, 629.11038668])

In [9]:
eig_vec

array([[ 0.6487899 , -0.65580225, -0.3859988 ],
       [-0.74104991, -0.4291978 , -0.51636642],
       [-0.17296443, -0.62105769,  0.7644414 ]])

In [10]:
eig_pairs = [(np.abs(eig_val[i]), eig_vec[:, i]) for i in range(len(eig_val))]
eig_pairs.sort(key=lambda x:x[0], reverse=True)

for i in eig_pairs:
    print(i[0])

910.0699530410361
629.1103866763253
44.81966028263878


In [15]:
matrix_w = np.hstack((eig_pairs[0][1].reshape(3, 1), eig_pairs[1][1].reshape(3, 1)))
print('Matrix W:\n', matrix_w)

Matrix W:
 [[-0.65580225 -0.3859988 ]
 [-0.4291978  -0.51636642]
 [-0.62105769  0.7644414 ]]


In [16]:
transformed = matrix_w.T.dot(marks-mean_marks.reshape(3, 1))
transformed

array([[-34.37098481,  -9.98345733,   3.93481353, -14.69691716,
         55.11654576],
       [ 13.66927088, -47.68820559,   2.31599277,  25.24923474,
          6.45370719]])

In [19]:
from sklearn.decomposition import PCA as sklearnPCA
sklearn_pca = sklearnPCA(n_components=2)
sklearn_transf = sklearn_pca.fit_transform(marks.T)
sklearn_transf

array([[-34.37098481, -13.66927088],
       [ -9.98345733,  47.68820559],
       [  3.93481353,  -2.31599277],
       [-14.69691716, -25.24923474],
       [ 55.11654576,  -6.45370719]])

In [20]:
sklearn_pca.components_

array([[-0.65580225, -0.4291978 , -0.62105769],
       [ 0.3859988 ,  0.51636642, -0.7644414 ]])

In [21]:
eig_val[:: -1].sort()
eig_val

array([910.06995304, 629.11038668,  44.81966028])

In [22]:
eig_val/eig_val.sum()

array([0.57453911, 0.39716565, 0.02829524])

In [23]:
sklearn_pca.explained_variance_ratio_

array([0.57453911, 0.39716565])

In [ ]:
sklearn_pca.explained_variance_ratio_.co